apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prom-grafana
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    # alb.ingress.kubernetes.io/subnets: "subnet-0aa439b4ddafcca10,subnet-0b95df318219145ca,subnet-0ccca36474902829a"
spec:
  ingressClassName: alb
  rules:
    - host: prom.deepaktyagi.tech
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stable-kube-prometheus-sta-prometheus
                port:
                  number: 9090
    - host: grafana.deepaktyagi.tech
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stable-grafana
                port:
                  number: 80
